language: cpp
os: linux
dist: focal

jobs:
  include:
  - addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-10
        - autotools-dev
    script:
    - export "CXX=g++-10"; ./configure --disable-lto && make check && sudo make install
  - addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - autotools-dev
        update: true
    before_install:
    - wget https://apt.llvm.org/llvm.sh && chmod +x llvm.sh && sudo ./llvm.sh 11
    script:
    - export "CXX=clang++-11"; ./configure --disable-lto && make check && sudo make install
